version: 2.1

commands:
  print_pipeline_id:
    steps:
      - run: echo $CIRCLE_WORKFLOW_ID

jobs:
  use_command_job:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - print_pipeline_id

  save_hello_myname_output:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo "my name is Mudit" >> ~/output1.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - output1.txt

  output_myname:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - attach_workspace:
          at: ~/
      - run: cat ~/output1.txt

workflows:
  myworkflow:
    jobs:
      - use_command_job
      - save_hello_myname_output
      - output_myname:
          requires:
            - save_hello_myname_output