version: 2.1

jobs:
  create_infrastructure: 
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Create Cloudformation Stack
          command: |
            aws cloudformation deploy \
              --template-file .circleci/template.yaml \
              --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
              --region us-east-1

# add permissions to user for stack creation in IAM
workflows:
  my_workflow:
    jobs:
      - create_infrastructure
      
